# Generated by Django 5.2.7 on 2025-10-14 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemItem',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
